site_name: PLACEHOLDER-YOUR-REPO
site_url: PLACEHOLDER-YOUR-REPO
site_description: AWS Concepts
site_author: PLACEHOLDER-YOUR-NAME
repo_name: PLACEHOLDER-YOUR-REPO
repo_url: PLACEHOLDER-YOUR-REPO
edit_uri: ''

nav:
  - template-gh-pages-mkdocs: index.md
  - 01. Page First: 01-page-first.md
  - 02. Page Second: 02-page-second.md

theme:
  language: en
  name: material
  logo: img/00-aws-logo.svg
  favicon: img/00-aws-logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Dark Mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Light Mode
  features:
    - search.suggest
    - search.highlight
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: PLACEHOLDER-YOUR-GITHUB-LINK
    - icon: fontawesome/brands/linkedin
      link: PLACEHOLDER-YOUR-LINKEDIN-LINK

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
